- 
  name: MC_ON_E1_INV
  method: MonteCarloOn
  epsilon_type: INV_VISIT_COUNT
  epsilon_initial: 1
  alpha_type: NOT_USED
  gamma: 1.0
- 
  name: MC_ON_E2_SCLD_50
  method: MonteCarloOn
  epsilon_type: INV_VISIT_COUNT_SCALED
  epsilon_initial: 1
  epsilon_n0: 50
  alpha_type: NOT_USED
  gamma: 1.0
- 
  name: MC_ON_E3_SCLD_200
  method: MonteCarloOn
  epsilon_type: INV_VISIT_COUNT_SCALED
  epsilon_initial: 1
  epsilon_n0: 200
  alpha_type: NOT_USED
  gamma: 1.0
- 
  name: MC_ON_E4_EXP_TARG_001
  method: MonteCarloOn
  epsilon_type: EXPONENTIAL_TARGET_AT
  epsilon_initial: 0.5
  epsilon_target: 0.001
  alpha_type: NOT_USED
  gamma: 1.0
- 
  name: MC_ON_E5_EXP_TARG_01
  method: MonteCarloOn
  epsilon_type: EXPONENTIAL_TARGET_AT
  epsilon_initial: 1
  epsilon_target: 0.01
  alpha_type: NOT_USED
  gamma: 1.0
