- 
  name: SARSA_E1_INV
  method: Sarsa
  epsilon_type: INV_VISIT_COUNT
  epsilon_initial: 1
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.1
  alpha_target: 0.005
  gamma: 1.0
- 
  name: SARSA_E2_SCLD_50
  method: Sarsa
  epsilon_type: INV_VISIT_COUNT_SCALED
  epsilon_initial: 1
  epsilon_n0: 50
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.1
  alpha_target: 0.005
  gamma: 1.0
- 
  name: SARSA_E3_SCLD_200
  method: Sarsa
  epsilon_type: INV_VISIT_COUNT_SCALED
  epsilon_initial: 1
  epsilon_n0: 200
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.1
  alpha_target: 0.005
  gamma: 1.0
- 
  name: SARSA_E4_EXP_TARG_001
  method: Sarsa
  epsilon_type: EXPONENTIAL_TARGET_AT
  epsilon_initial: 0.5
  epsilon_target: 0.001
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.1
  alpha_target: 0.005
  gamma: 1.0
- 
  name: SARSA_E5_EXP_TARG_01
  method: Sarsa
  epsilon_type: EXPONENTIAL_TARGET_AT
  epsilon_initial: 1
  epsilon_target: 0.01
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.1
  alpha_target: 0.005
  gamma: 1.0
