- 
  name: Q_LEARNING
  method: Qlearning
  epsilon_type: CONSTANT
  epsilon_constant: 1
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.1
  alpha_target: 0.005
  gamma: 1.0
- 
  name: SARSA
  method: Sarsa
  epsilon_type: INV_ROUNDS_TARGET_AT
  epsilon_initial: 0.5
  epsilon_target: 0.05
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.1
  alpha_target: 0.005
  gamma: 1.0
- 
  name: SARSA_EXP
  method: SarsaExpected
  epsilon_type: INV_ROUNDS_TARGET_AT
  epsilon_initial: 0.5
  epsilon_target: 0.05
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.1
  alpha_target: 0.005
  gamma: 1.0
- 
  name: SG_SARSA_FC
  method: SgFcSarsa
  epsilon_type: INV_ROUNDS_TARGET_AT
  epsilon_initial: 0.5
  epsilon_target: 0.05
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.03
  alpha_target: 0.001
  gamma: 1.0
-
  name: SG_SARSA_TC
  method: SgTcSarsa
  epsilon_type: INV_ROUNDS_TARGET_AT
  epsilon_initial: 0.5
  epsilon_target: 0.05
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.03
  alpha_target: 0.001
  gamma: 1.0
-
  name: SG_SARSA_POL
  method: SgPolSarsa
  epsilon_type: INV_ROUNDS_TARGET_AT
  epsilon_initial: 0.5
  epsilon_target: 0.05
  alpha_type: EXPONENTIAL_TARGET_AT
  alpha_initial: 0.03
  alpha_target: 0.001
  gamma: 1.0
